import { type NextPage } from "next";
import React, { useEffect, useContext, useState } from 'react';
import Head from "next/head";

import { CrowdFundingContext } from "context/CrowdFunding.js";
import { Navbar, Footer, Hero, Card, PopUp } from "components";

const Home: NextPage = () => {
  const {
    titleData,
    getCampaigns,
    createCampaign,
    donate,
    getUserCampaigns,
    getDonations,
  } = useContext(CrowdFundingContext);

  const [allcampaign, setAllcampaign] = useState();
  const [usercampaign, setUsercampaign] = useState();

  //Had to put the asynchronous logic inside a seperate function 'fetchData' to be compatiable with the useEffect hook
  useEffect(() => {
    const fetchData = async () => {
      const getCampaignsData = getCampaigns();
      const userCampaignsData = getUserCampaigns();
      const allData = await getCampaignsData;
      const userData = await userCampaignsData;
      setAllcampaign(allData);
      setUsercampaign(userData);
    };
    fetchData();

    return () => {
    };
  }, []);

  //Donation popup model
  const [openModel, setOpenModel] = useState(false);
  const [donateCampaign, setDonateCampaign] = useState();
  console.log(donateCampaign);

  return (
    <>
      <Head>
        <title>Web3 Giving</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`relative flex flex-col items-center justify-center`}>
        <Navbar />
        <Hero titleData={titleData} createCampaign={createCampaign} />
        <Card 
          title="All Listed Campaign"
          allcampaign={allcampaign}
          setOpenModel={setOpenModel}
          setDonate={setDonateCampaign}
        />
        <Card
          title="Your Created Campaign"
          allcampaign={usercampaign}
          setOpenModel={setOpenModel}
          setDonate={setDonateCampaign}
        />
        {openModel && (
          <PopUp 
            setOpenModel={setOpenModel}
            getDonations={getDonations}
            donate={donateCampaign}
            donateFunction={donate}
          />
        )}
        <Footer />
      </main>
    </>
  );
};

export default Home;
