import { type NextPage } from "next";
import Head from "next/head";
import { Navbar, Footer } from "components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web3 Crowdfunding</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Navbar />
        <Footer />
      </main>
    </>
  );
};

export default Home;
